= APOD Fetcher
sewpalu <sewpalu@gmail.com>
:source-highlighter: rouge

== About

This aims to be a simple solution to fetching NASAs APoD (Astronomical Picture of the Day) which is to my knowledge only published through HTML-Pages containing the Picture ... so some HTML parsing is required to extract the image URL.

.Dependencies
* libcurl
* Googles Gumbo HTML-Parser (Arch package: `gumbo-parser`)

== Build

[source,sh]
----
make build
----

== Install

[source,sh]
----
make install BIN_INSTALL_DIR=/path/where/the/executable/is/put
----

Make sure the value assigned to `BIN_INSTALL_DIR` is in your `PATH` if you want to invoke the program without specifying the executables location.

== Example usage

[source,sh]
----
# Invoke
apod_fetch out_file

# Set output as wallpaper
feh --bg-max out_file
----

== Example use case

Update the desktop wallpaper automatically to the current APoD using systemd timers.

.Example systemd timer `~/.config/systemd/user/apod_fetch.timer`
[source,conf]
----
[Unit]
Description=Run apod_fetch to update the wallpaper
Requires=apod_fetch.service

[Timer]
OnStartupSec=1min
OnUnitActiveSec=6h

[Install]
WantedBy=timers.target
----

.Corresponding service `~/.config/systemd/user/apod_fetch.service`
[source,conf]
----
[Unit]
Description=Fetch the APoD and set it as the wallpaper

[Service]
Type=oneshot
ExecStart=/path/to/apod_fetch %h/.apod
ExecStart=sh -c "test -f %h/.apod && feh --image-bg \"#272d2d\" --bg-max %h/.apod"

[Install]
WantedBy=default.target
----

.Enable and start with
[source,sh]
----
systemctl --user enable apod_fetch.timer
systemctl --user start apod_fetch.timer
----

